// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.3
// source: Service.proto

package Protoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProtoService_Enc_FullMethodName     = "/ProtoStruct.ProtoService/Enc"
	ProtoService_EncData_FullMethodName = "/ProtoStruct.ProtoService/EncData"
	ProtoService_DecData_FullMethodName = "/ProtoStruct.ProtoService/DecData"
	ProtoService_GetPP_FullMethodName   = "/ProtoStruct.ProtoService/GetPP"
	ProtoService_GetUSK_FullMethodName  = "/ProtoStruct.ProtoService/GetUSK"
	ProtoService_SetPP_FullMethodName   = "/ProtoStruct.ProtoService/SetPP"
	ProtoService_SetUSK_FullMethodName  = "/ProtoStruct.ProtoService/SetUSK"
)

// ProtoServiceClient is the client API for ProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtoServiceClient interface {
	Enc(ctx context.Context, in *Element, opts ...grpc.CallOption) (*Element, error)
	EncData(ctx context.Context, in *DataMessage, opts ...grpc.CallOption) (*CTMessage, error)
	DecData(ctx context.Context, in *CTMessage, opts ...grpc.CallOption) (*DataMessage, error)
	GetPP(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*PPMessage, error)
	GetUSK(ctx context.Context, in *AttributeMessage, opts ...grpc.CallOption) (*USKMessage, error)
	SetPP(ctx context.Context, in *PPMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
	SetUSK(ctx context.Context, in *USKMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type protoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoServiceClient(cc grpc.ClientConnInterface) ProtoServiceClient {
	return &protoServiceClient{cc}
}

func (c *protoServiceClient) Enc(ctx context.Context, in *Element, opts ...grpc.CallOption) (*Element, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Element)
	err := c.cc.Invoke(ctx, ProtoService_Enc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoServiceClient) EncData(ctx context.Context, in *DataMessage, opts ...grpc.CallOption) (*CTMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CTMessage)
	err := c.cc.Invoke(ctx, ProtoService_EncData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoServiceClient) DecData(ctx context.Context, in *CTMessage, opts ...grpc.CallOption) (*DataMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataMessage)
	err := c.cc.Invoke(ctx, ProtoService_DecData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoServiceClient) GetPP(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*PPMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PPMessage)
	err := c.cc.Invoke(ctx, ProtoService_GetPP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoServiceClient) GetUSK(ctx context.Context, in *AttributeMessage, opts ...grpc.CallOption) (*USKMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(USKMessage)
	err := c.cc.Invoke(ctx, ProtoService_GetUSK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoServiceClient) SetPP(ctx context.Context, in *PPMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, ProtoService_SetPP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoServiceClient) SetUSK(ctx context.Context, in *USKMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, ProtoService_SetUSK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoServiceServer is the server API for ProtoService service.
// All implementations must embed UnimplementedProtoServiceServer
// for forward compatibility.
type ProtoServiceServer interface {
	Enc(context.Context, *Element) (*Element, error)
	EncData(context.Context, *DataMessage) (*CTMessage, error)
	DecData(context.Context, *CTMessage) (*DataMessage, error)
	GetPP(context.Context, *EmptyMessage) (*PPMessage, error)
	GetUSK(context.Context, *AttributeMessage) (*USKMessage, error)
	SetPP(context.Context, *PPMessage) (*EmptyMessage, error)
	SetUSK(context.Context, *USKMessage) (*EmptyMessage, error)
	mustEmbedUnimplementedProtoServiceServer()
}

// UnimplementedProtoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtoServiceServer struct{}

func (UnimplementedProtoServiceServer) Enc(context.Context, *Element) (*Element, error) {
	return nil, status.Error(codes.Unimplemented, "method Enc not implemented")
}
func (UnimplementedProtoServiceServer) EncData(context.Context, *DataMessage) (*CTMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method EncData not implemented")
}
func (UnimplementedProtoServiceServer) DecData(context.Context, *CTMessage) (*DataMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method DecData not implemented")
}
func (UnimplementedProtoServiceServer) GetPP(context.Context, *EmptyMessage) (*PPMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPP not implemented")
}
func (UnimplementedProtoServiceServer) GetUSK(context.Context, *AttributeMessage) (*USKMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUSK not implemented")
}
func (UnimplementedProtoServiceServer) SetPP(context.Context, *PPMessage) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPP not implemented")
}
func (UnimplementedProtoServiceServer) SetUSK(context.Context, *USKMessage) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUSK not implemented")
}
func (UnimplementedProtoServiceServer) mustEmbedUnimplementedProtoServiceServer() {}
func (UnimplementedProtoServiceServer) testEmbeddedByValue()                      {}

// UnsafeProtoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtoServiceServer will
// result in compilation errors.
type UnsafeProtoServiceServer interface {
	mustEmbedUnimplementedProtoServiceServer()
}

func RegisterProtoServiceServer(s grpc.ServiceRegistrar, srv ProtoServiceServer) {
	// If the following call panics, it indicates UnimplementedProtoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtoService_ServiceDesc, srv)
}

func _ProtoService_Enc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Element)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoServiceServer).Enc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoService_Enc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoServiceServer).Enc(ctx, req.(*Element))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoService_EncData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoServiceServer).EncData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoService_EncData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoServiceServer).EncData(ctx, req.(*DataMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoService_DecData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CTMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoServiceServer).DecData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoService_DecData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoServiceServer).DecData(ctx, req.(*CTMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoService_GetPP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoServiceServer).GetPP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoService_GetPP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoServiceServer).GetPP(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoService_GetUSK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttributeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoServiceServer).GetUSK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoService_GetUSK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoServiceServer).GetUSK(ctx, req.(*AttributeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoService_SetPP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PPMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoServiceServer).SetPP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoService_SetPP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoServiceServer).SetPP(ctx, req.(*PPMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoService_SetUSK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(USKMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoServiceServer).SetUSK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoService_SetUSK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoServiceServer).SetUSK(ctx, req.(*USKMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtoService_ServiceDesc is the grpc.ServiceDesc for ProtoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ProtoStruct.ProtoService",
	HandlerType: (*ProtoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enc",
			Handler:    _ProtoService_Enc_Handler,
		},
		{
			MethodName: "EncData",
			Handler:    _ProtoService_EncData_Handler,
		},
		{
			MethodName: "DecData",
			Handler:    _ProtoService_DecData_Handler,
		},
		{
			MethodName: "GetPP",
			Handler:    _ProtoService_GetPP_Handler,
		},
		{
			MethodName: "GetUSK",
			Handler:    _ProtoService_GetUSK_Handler,
		},
		{
			MethodName: "SetPP",
			Handler:    _ProtoService_SetPP_Handler,
		},
		{
			MethodName: "SetUSK",
			Handler:    _ProtoService_SetUSK_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Service.proto",
}
