// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: Service.proto

package Protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Element struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         []byte                 `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Element) Reset() {
	*x = Element{}
	mi := &file_Service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_Service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_Service_proto_rawDescGZIP(), []int{0}
}

func (x *Element) GetPoint() []byte {
	if x != nil {
		return x.Point
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elems         [][]byte               `protobuf:"bytes,1,rep,name=elems,proto3" json:"elems,omitempty"` // 一行 Zr 元素（每个是 element_to_bytes 的结果）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_Service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_Service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_Service_proto_rawDescGZIP(), []int{1}
}

func (x *Row) GetElems() [][]byte {
	if x != nil {
		return x.Elems
	}
	return nil
}

type CTMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C             []byte                 `protobuf:"bytes,1,opt,name=C,proto3" json:"C,omitempty"`             // GT: element_to_bytes
	CC            []byte                 `protobuf:"bytes,2,opt,name=CC,proto3" json:"CC,omitempty"`           // G1: element_to_bytes
	Cs            [][]byte               `protobuf:"bytes,3,rep,name=Cs,proto3" json:"Cs,omitempty"`           // vector<G1>
	Ds            [][]byte               `protobuf:"bytes,4,rep,name=Ds,proto3" json:"Ds,omitempty"`           // vector<G1>
	M             []*Row                 `protobuf:"bytes,5,rep,name=M,proto3" json:"M,omitempty"`             // matrix<Zr> 按行存
	Rho           []int32                `protobuf:"varint,6,rep,packed,name=rho,proto3" json:"rho,omitempty"` // vector<int>
	Skct          []byte                 `protobuf:"bytes,7,opt,name=skct,proto3" json:"skct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTMessage) Reset() {
	*x = CTMessage{}
	mi := &file_Service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTMessage) ProtoMessage() {}

func (x *CTMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTMessage.ProtoReflect.Descriptor instead.
func (*CTMessage) Descriptor() ([]byte, []int) {
	return file_Service_proto_rawDescGZIP(), []int{2}
}

func (x *CTMessage) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *CTMessage) GetCC() []byte {
	if x != nil {
		return x.CC
	}
	return nil
}

func (x *CTMessage) GetCs() [][]byte {
	if x != nil {
		return x.Cs
	}
	return nil
}

func (x *CTMessage) GetDs() [][]byte {
	if x != nil {
		return x.Ds
	}
	return nil
}

func (x *CTMessage) GetM() []*Row {
	if x != nil {
		return x.M
	}
	return nil
}

func (x *CTMessage) GetRho() []int32 {
	if x != nil {
		return x.Rho
	}
	return nil
}

func (x *CTMessage) GetSkct() []byte {
	if x != nil {
		return x.Skct
	}
	return nil
}

type AttributeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     []bool                 `protobuf:"varint,1,rep,packed,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeMessage) Reset() {
	*x = AttributeMessage{}
	mi := &file_Service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeMessage) ProtoMessage() {}

func (x *AttributeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeMessage.ProtoReflect.Descriptor instead.
func (*AttributeMessage) Descriptor() ([]byte, []int) {
	return file_Service_proto_rawDescGZIP(), []int{3}
}

func (x *AttributeMessage) GetAttribute() []bool {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type USKMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	K             []byte                 `protobuf:"bytes,1,opt,name=K,proto3" json:"K,omitempty"`
	L             []byte                 `protobuf:"bytes,2,opt,name=L,proto3" json:"L,omitempty"`
	Sk            [][]byte               `protobuf:"bytes,3,rep,name=sk,proto3" json:"sk,omitempty"`
	Attribute     []bool                 `protobuf:"varint,4,rep,packed,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *USKMessage) Reset() {
	*x = USKMessage{}
	mi := &file_Service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *USKMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USKMessage) ProtoMessage() {}

func (x *USKMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USKMessage.ProtoReflect.Descriptor instead.
func (*USKMessage) Descriptor() ([]byte, []int) {
	return file_Service_proto_rawDescGZIP(), []int{4}
}

func (x *USKMessage) GetK() []byte {
	if x != nil {
		return x.K
	}
	return nil
}

func (x *USKMessage) GetL() []byte {
	if x != nil {
		return x.L
	}
	return nil
}

func (x *USKMessage) GetSk() [][]byte {
	if x != nil {
		return x.Sk
	}
	return nil
}

func (x *USKMessage) GetAttribute() []bool {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type PPMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	G             []byte                 `protobuf:"bytes,1,opt,name=g,proto3" json:"g,omitempty"`   // generator
	Ga            []byte                 `protobuf:"bytes,2,opt,name=ga,proto3" json:"ga,omitempty"` // g^a
	H             [][]byte               `protobuf:"bytes,3,rep,name=h,proto3" json:"h,omitempty"`   // h1,h2,h3,...
	Talpha        []byte                 `protobuf:"bytes,4,opt,name=talpha,proto3" json:"talpha,omitempty"`
	U             int32                  `protobuf:"varint,5,opt,name=u,proto3" json:"u,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PPMessage) Reset() {
	*x = PPMessage{}
	mi := &file_Service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PPMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPMessage) ProtoMessage() {}

func (x *PPMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPMessage.ProtoReflect.Descriptor instead.
func (*PPMessage) Descriptor() ([]byte, []int) {
	return file_Service_proto_rawDescGZIP(), []int{5}
}

func (x *PPMessage) GetG() []byte {
	if x != nil {
		return x.G
	}
	return nil
}

func (x *PPMessage) GetGa() []byte {
	if x != nil {
		return x.Ga
	}
	return nil
}

func (x *PPMessage) GetH() [][]byte {
	if x != nil {
		return x.H
	}
	return nil
}

func (x *PPMessage) GetTalpha() []byte {
	if x != nil {
		return x.Talpha
	}
	return nil
}

func (x *PPMessage) GetU() int32 {
	if x != nil {
		return x.U
	}
	return 0
}

type DataMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataMessage) Reset() {
	*x = DataMessage{}
	mi := &file_Service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMessage) ProtoMessage() {}

func (x *DataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMessage.ProtoReflect.Descriptor instead.
func (*DataMessage) Descriptor() ([]byte, []int) {
	return file_Service_proto_rawDescGZIP(), []int{6}
}

func (x *DataMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_Service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_Service_proto_rawDescGZIP(), []int{7}
}

var File_Service_proto protoreflect.FileDescriptor

const file_Service_proto_rawDesc = "" +
	"\n" +
	"\rService.proto\x12\vProtoStruct\"\x1f\n" +
	"\aElement\x12\x14\n" +
	"\x05point\x18\x01 \x01(\fR\x05point\"\x1b\n" +
	"\x03Row\x12\x14\n" +
	"\x05elems\x18\x01 \x03(\fR\x05elems\"\x8f\x01\n" +
	"\tCTMessage\x12\f\n" +
	"\x01C\x18\x01 \x01(\fR\x01C\x12\x0e\n" +
	"\x02CC\x18\x02 \x01(\fR\x02CC\x12\x0e\n" +
	"\x02Cs\x18\x03 \x03(\fR\x02Cs\x12\x0e\n" +
	"\x02Ds\x18\x04 \x03(\fR\x02Ds\x12\x1e\n" +
	"\x01M\x18\x05 \x03(\v2\x10.ProtoStruct.RowR\x01M\x12\x10\n" +
	"\x03rho\x18\x06 \x03(\x05R\x03rho\x12\x12\n" +
	"\x04skct\x18\a \x01(\fR\x04skct\"0\n" +
	"\x10AttributeMessage\x12\x1c\n" +
	"\tattribute\x18\x01 \x03(\bR\tattribute\"V\n" +
	"\n" +
	"USKMessage\x12\f\n" +
	"\x01K\x18\x01 \x01(\fR\x01K\x12\f\n" +
	"\x01L\x18\x02 \x01(\fR\x01L\x12\x0e\n" +
	"\x02sk\x18\x03 \x03(\fR\x02sk\x12\x1c\n" +
	"\tattribute\x18\x04 \x03(\bR\tattribute\"]\n" +
	"\tPPMessage\x12\f\n" +
	"\x01g\x18\x01 \x01(\fR\x01g\x12\x0e\n" +
	"\x02ga\x18\x02 \x01(\fR\x02ga\x12\f\n" +
	"\x01h\x18\x03 \x03(\fR\x01h\x12\x16\n" +
	"\x06talpha\x18\x04 \x01(\fR\x06talpha\x12\f\n" +
	"\x01u\x18\x05 \x01(\x05R\x01u\"!\n" +
	"\vDataMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x0e\n" +
	"\fEmptyMessage2\xb3\x03\n" +
	"\fProtoService\x121\n" +
	"\x03Enc\x12\x14.ProtoStruct.Element\x1a\x14.ProtoStruct.Element\x12;\n" +
	"\aEncData\x12\x18.ProtoStruct.DataMessage\x1a\x16.ProtoStruct.CTMessage\x12;\n" +
	"\aDecData\x12\x16.ProtoStruct.CTMessage\x1a\x18.ProtoStruct.DataMessage\x12:\n" +
	"\x05GetPP\x12\x19.ProtoStruct.EmptyMessage\x1a\x16.ProtoStruct.PPMessage\x12@\n" +
	"\x06GetUSK\x12\x1d.ProtoStruct.AttributeMessage\x1a\x17.ProtoStruct.USKMessage\x12:\n" +
	"\x05SetPP\x12\x16.ProtoStruct.PPMessage\x1a\x19.ProtoStruct.EmptyMessage\x12<\n" +
	"\x06SetUSK\x12\x17.ProtoStruct.USKMessage\x1a\x19.ProtoStruct.EmptyMessageB\x1bZ\x19GoInterface/Protoc;Protocb\x06proto3"

var (
	file_Service_proto_rawDescOnce sync.Once
	file_Service_proto_rawDescData []byte
)

func file_Service_proto_rawDescGZIP() []byte {
	file_Service_proto_rawDescOnce.Do(func() {
		file_Service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Service_proto_rawDesc), len(file_Service_proto_rawDesc)))
	})
	return file_Service_proto_rawDescData
}

var file_Service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_Service_proto_goTypes = []any{
	(*Element)(nil),          // 0: ProtoStruct.Element
	(*Row)(nil),              // 1: ProtoStruct.Row
	(*CTMessage)(nil),        // 2: ProtoStruct.CTMessage
	(*AttributeMessage)(nil), // 3: ProtoStruct.AttributeMessage
	(*USKMessage)(nil),       // 4: ProtoStruct.USKMessage
	(*PPMessage)(nil),        // 5: ProtoStruct.PPMessage
	(*DataMessage)(nil),      // 6: ProtoStruct.DataMessage
	(*EmptyMessage)(nil),     // 7: ProtoStruct.EmptyMessage
}
var file_Service_proto_depIdxs = []int32{
	1, // 0: ProtoStruct.CTMessage.M:type_name -> ProtoStruct.Row
	0, // 1: ProtoStruct.ProtoService.Enc:input_type -> ProtoStruct.Element
	6, // 2: ProtoStruct.ProtoService.EncData:input_type -> ProtoStruct.DataMessage
	2, // 3: ProtoStruct.ProtoService.DecData:input_type -> ProtoStruct.CTMessage
	7, // 4: ProtoStruct.ProtoService.GetPP:input_type -> ProtoStruct.EmptyMessage
	3, // 5: ProtoStruct.ProtoService.GetUSK:input_type -> ProtoStruct.AttributeMessage
	5, // 6: ProtoStruct.ProtoService.SetPP:input_type -> ProtoStruct.PPMessage
	4, // 7: ProtoStruct.ProtoService.SetUSK:input_type -> ProtoStruct.USKMessage
	0, // 8: ProtoStruct.ProtoService.Enc:output_type -> ProtoStruct.Element
	2, // 9: ProtoStruct.ProtoService.EncData:output_type -> ProtoStruct.CTMessage
	6, // 10: ProtoStruct.ProtoService.DecData:output_type -> ProtoStruct.DataMessage
	5, // 11: ProtoStruct.ProtoService.GetPP:output_type -> ProtoStruct.PPMessage
	4, // 12: ProtoStruct.ProtoService.GetUSK:output_type -> ProtoStruct.USKMessage
	7, // 13: ProtoStruct.ProtoService.SetPP:output_type -> ProtoStruct.EmptyMessage
	7, // 14: ProtoStruct.ProtoService.SetUSK:output_type -> ProtoStruct.EmptyMessage
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Service_proto_init() }
func file_Service_proto_init() {
	if File_Service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Service_proto_rawDesc), len(file_Service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Service_proto_goTypes,
		DependencyIndexes: file_Service_proto_depIdxs,
		MessageInfos:      file_Service_proto_msgTypes,
	}.Build()
	File_Service_proto = out.File
	file_Service_proto_goTypes = nil
	file_Service_proto_depIdxs = nil
}
